# Generated by Django 2.2 on 2019-08-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('nic', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('email', models.CharField(default=None, max_length=200, unique=True)),
                ('f_name', models.CharField(max_length=200)),
                ('l_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
