# Generated by Django 3.0.dev20190819050343 on 2019-08-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responseapp', '0002_auto_20190821_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
    ]
