# Generated by Django 2.2 on 2019-08-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterDetails',
            fields=[
                ('details', models.CharField(blank=True, max_length=300, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'filter_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FilterEmployee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nic', models.CharField(blank=True, max_length=12, null=True)),
                ('f_name', models.CharField(blank=True, max_length=200, null=True)),
                ('l_name', models.CharField(blank=True, max_length=200, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'filter_employee',
                'managed': False,
            },
        ),
    ]
